// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(vouch_coreFFI)
import vouch_coreFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_vouch_core_uniffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_vouch_core_uniffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


public struct DecodedKey {
    public var algorithm: String
    public var rawKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(algorithm: String, rawKey: Data) {
        self.algorithm = algorithm
        self.rawKey = rawKey
    }
}



extension DecodedKey: Equatable, Hashable {
    public static func ==(lhs: DecodedKey, rhs: DecodedKey) -> Bool {
        if lhs.algorithm != rhs.algorithm {
            return false
        }
        if lhs.rawKey != rhs.rawKey {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(algorithm)
        hasher.combine(rawKey)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDecodedKey: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DecodedKey {
        return
            try DecodedKey(
                algorithm: FfiConverterString.read(from: &buf), 
                rawKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: DecodedKey, into buf: inout [UInt8]) {
        FfiConverterString.write(value.algorithm, into: &buf)
        FfiConverterData.write(value.rawKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecodedKey_lift(_ buf: RustBuffer) throws -> DecodedKey {
    return try FfiConverterTypeDecodedKey.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDecodedKey_lower(_ value: DecodedKey) -> RustBuffer {
    return FfiConverterTypeDecodedKey.lower(value)
}


public struct Ed25519KeyPair {
    public var seed: Data
    public var publicKey: Data
    public var multikey: String
    public var didKey: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(seed: Data, publicKey: Data, multikey: String, didKey: String) {
        self.seed = seed
        self.publicKey = publicKey
        self.multikey = multikey
        self.didKey = didKey
    }
}



extension Ed25519KeyPair: Equatable, Hashable {
    public static func ==(lhs: Ed25519KeyPair, rhs: Ed25519KeyPair) -> Bool {
        if lhs.seed != rhs.seed {
            return false
        }
        if lhs.publicKey != rhs.publicKey {
            return false
        }
        if lhs.multikey != rhs.multikey {
            return false
        }
        if lhs.didKey != rhs.didKey {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(seed)
        hasher.combine(publicKey)
        hasher.combine(multikey)
        hasher.combine(didKey)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEd25519KeyPair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Ed25519KeyPair {
        return
            try Ed25519KeyPair(
                seed: FfiConverterData.read(from: &buf), 
                publicKey: FfiConverterData.read(from: &buf), 
                multikey: FfiConverterString.read(from: &buf), 
                didKey: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: Ed25519KeyPair, into buf: inout [UInt8]) {
        FfiConverterData.write(value.seed, into: &buf)
        FfiConverterData.write(value.publicKey, into: &buf)
        FfiConverterString.write(value.multikey, into: &buf)
        FfiConverterString.write(value.didKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEd25519KeyPair_lift(_ buf: RustBuffer) throws -> Ed25519KeyPair {
    return try FfiConverterTypeEd25519KeyPair.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEd25519KeyPair_lower(_ value: Ed25519KeyPair) -> RustBuffer {
    return FfiConverterTypeEd25519KeyPair.lower(value)
}


public struct MlDsaKeyPair {
    public var secretKey: Data
    public var publicKey: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(secretKey: Data, publicKey: Data) {
        self.secretKey = secretKey
        self.publicKey = publicKey
    }
}



extension MlDsaKeyPair: Equatable, Hashable {
    public static func ==(lhs: MlDsaKeyPair, rhs: MlDsaKeyPair) -> Bool {
        if lhs.secretKey != rhs.secretKey {
            return false
        }
        if lhs.publicKey != rhs.publicKey {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(secretKey)
        hasher.combine(publicKey)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMlDsaKeyPair: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MlDsaKeyPair {
        return
            try MlDsaKeyPair(
                secretKey: FfiConverterData.read(from: &buf), 
                publicKey: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: MlDsaKeyPair, into buf: inout [UInt8]) {
        FfiConverterData.write(value.secretKey, into: &buf)
        FfiConverterData.write(value.publicKey, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlDsaKeyPair_lift(_ buf: RustBuffer) throws -> MlDsaKeyPair {
    return try FfiConverterTypeMlDsaKeyPair.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMlDsaKeyPair_lower(_ value: MlDsaKeyPair) -> RustBuffer {
    return FfiConverterTypeMlDsaKeyPair.lower(value)
}


public struct VerifyResult {
    public var proofValid: Bool
    public var timeValid: Bool
    public var valid: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(proofValid: Bool, timeValid: Bool, valid: Bool) {
        self.proofValid = proofValid
        self.timeValid = timeValid
        self.valid = valid
    }
}



extension VerifyResult: Equatable, Hashable {
    public static func ==(lhs: VerifyResult, rhs: VerifyResult) -> Bool {
        if lhs.proofValid != rhs.proofValid {
            return false
        }
        if lhs.timeValid != rhs.timeValid {
            return false
        }
        if lhs.valid != rhs.valid {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(proofValid)
        hasher.combine(timeValid)
        hasher.combine(valid)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVerifyResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VerifyResult {
        return
            try VerifyResult(
                proofValid: FfiConverterBool.read(from: &buf), 
                timeValid: FfiConverterBool.read(from: &buf), 
                valid: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: VerifyResult, into buf: inout [UInt8]) {
        FfiConverterBool.write(value.proofValid, into: &buf)
        FfiConverterBool.write(value.timeValid, into: &buf)
        FfiConverterBool.write(value.valid, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerifyResult_lift(_ buf: RustBuffer) throws -> VerifyResult {
    return try FfiConverterTypeVerifyResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVerifyResult_lower(_ value: VerifyResult) -> RustBuffer {
    return FfiConverterTypeVerifyResult.lower(value)
}


public enum CoreError {

    
    
    case Core(message: String)
    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCoreError: FfiConverterRustBuffer {
    typealias SwiftType = CoreError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CoreError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Core(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CoreError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .Core(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))

        
        }
    }
}


extension CoreError: Equatable, Hashable {}

extension CoreError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}
public func buildDelegationLink(issuer: String, subject: String, intentJson: String, validFrom: String?, validUntil: String?, parentProofValue: String?)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_build_delegation_link(
        FfiConverterString.lower(issuer),
        FfiConverterString.lower(subject),
        FfiConverterString.lower(intentJson),
        FfiConverterOptionString.lower(validFrom),
        FfiConverterOptionString.lower(validUntil),
        FfiConverterOptionString.lower(parentProofValue),$0
    )
})
}
public func buildProof(credentialJson: String, seed: Data, verificationMethod: String, created: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_build_proof(
        FfiConverterString.lower(credentialJson),
        FfiConverterData.lower(seed),
        FfiConverterString.lower(verificationMethod),
        FfiConverterString.lower(created),$0
    )
})
}
public func canonicalize(json: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_canonicalize(
        FfiConverterString.lower(json),$0
    )
})
}
public func decodeMultikey(multikey: String)throws  -> DecodedKey {
    return try  FfiConverterTypeDecodedKey.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_decode_multikey(
        FfiConverterString.lower(multikey),$0
    )
})
}
public func didKeyFromEd25519(publicKey: Data)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_did_key_from_ed25519(
        FfiConverterData.lower(publicKey),$0
    )
})
}
public func ed25519FromDidKey(did: String)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_ed25519_from_did_key(
        FfiConverterString.lower(did),$0
    )
})
}
public func ed25519Sign(seed: Data, message: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_ed25519_sign(
        FfiConverterData.lower(seed),
        FfiConverterData.lower(message),$0
    )
})
}
public func ed25519Verify(publicKey: Data, message: Data, signature: Data)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_ed25519_verify(
        FfiConverterData.lower(publicKey),
        FfiConverterData.lower(message),
        FfiConverterData.lower(signature),$0
    )
})
}
public func encodeEd25519Multikey(publicKey: Data)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_encode_ed25519_multikey(
        FfiConverterData.lower(publicKey),$0
    )
})
}
public func generateEd25519()throws  -> Ed25519KeyPair {
    return try  FfiConverterTypeEd25519KeyPair.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_generate_ed25519($0
    )
})
}
public func generateMldsa44()throws  -> MlDsaKeyPair {
    return try  FfiConverterTypeMlDsaKeyPair.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_generate_mldsa44($0
    )
})
}
public func mldsa44Sign(secret: Data, publicKey: Data, message: Data)throws  -> Data {
    return try  FfiConverterData.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_mldsa44_sign(
        FfiConverterData.lower(secret),
        FfiConverterData.lower(publicKey),
        FfiConverterData.lower(message),$0
    )
})
}
public func mldsa44Verify(publicKey: Data, message: Data, signature: Data)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_mldsa44_verify(
        FfiConverterData.lower(publicKey),
        FfiConverterData.lower(message),
        FfiConverterData.lower(signature),$0
    )
})
}
public func signCredential(credentialJson: String, seed: Data, verificationMethod: String, created: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_sign_credential(
        FfiConverterString.lower(credentialJson),
        FfiConverterData.lower(seed),
        FfiConverterString.lower(verificationMethod),
        FfiConverterString.lower(created),$0
    )
})
}
public func signDual(credentialJson: String, ed25519Seed: Data, mldsaSecret: Data, mldsaPublic: Data, ed25519Vm: String, mldsaVm: String, created: String)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_sign_dual(
        FfiConverterString.lower(credentialJson),
        FfiConverterData.lower(ed25519Seed),
        FfiConverterData.lower(mldsaSecret),
        FfiConverterData.lower(mldsaPublic),
        FfiConverterString.lower(ed25519Vm),
        FfiConverterString.lower(mldsaVm),
        FfiConverterString.lower(created),$0
    )
})
}
public func verifyChainTimeBound(chainJson: String, nowIso: String, clockSkewSeconds: Int64)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_verify_chain_time_bound(
        FfiConverterString.lower(chainJson),
        FfiConverterString.lower(nowIso),
        FfiConverterInt64.lower(clockSkewSeconds),$0
    )
})
}
public func verifyComposite(credentialJson: String, ed25519Public: Data, mldsaPublic: Data)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_verify_composite(
        FfiConverterString.lower(credentialJson),
        FfiConverterData.lower(ed25519Public),
        FfiConverterData.lower(mldsaPublic),$0
    )
})
}
public func verifyCredential(credentialJson: String, publicKey: Data, nowIso: String, clockSkewSeconds: Int64)throws  -> VerifyResult {
    return try  FfiConverterTypeVerifyResult.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_verify_credential(
        FfiConverterString.lower(credentialJson),
        FfiConverterData.lower(publicKey),
        FfiConverterString.lower(nowIso),
        FfiConverterInt64.lower(clockSkewSeconds),$0
    )
})
}
public func verifyDual(credentialJson: String, ed25519Public: Data, mldsaPublic: Data)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_verify_dual(
        FfiConverterString.lower(credentialJson),
        FfiConverterData.lower(ed25519Public),
        FfiConverterData.lower(mldsaPublic),$0
    )
})
}
public func verifyProof(credentialJson: String, publicKey: Data)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_verify_proof(
        FfiConverterString.lower(credentialJson),
        FfiConverterData.lower(publicKey),$0
    )
})
}
public func verifyStatus(credentialStatusJson: String, statusListCredentialJson: String)throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeCoreError.lift) {
    uniffi_vouch_core_uniffi_fn_func_verify_status(
        FfiConverterString.lower(credentialStatusJson),
        FfiConverterString.lower(statusListCredentialJson),$0
    )
})
}
public func version() -> String {
    return try!  FfiConverterString.lift(try! rustCall() {
    uniffi_vouch_core_uniffi_fn_func_version($0
    )
})
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_vouch_core_uniffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_build_delegation_link() != 50660) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_build_proof() != 35325) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_canonicalize() != 47212) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_decode_multikey() != 44008) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_did_key_from_ed25519() != 37859) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_ed25519_from_did_key() != 47932) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_ed25519_sign() != 16791) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_ed25519_verify() != 60021) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_encode_ed25519_multikey() != 17041) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_generate_ed25519() != 21605) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_generate_mldsa44() != 55783) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_mldsa44_sign() != 64988) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_mldsa44_verify() != 56375) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_sign_credential() != 57541) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_sign_dual() != 32161) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_verify_chain_time_bound() != 45726) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_verify_composite() != 16114) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_verify_credential() != 17868) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_verify_dual() != 159) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_verify_proof() != 22681) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_verify_status() != 26347) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_vouch_core_uniffi_checksum_func_version() != 28413) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all